version=1.1.5
group=se.itssimple.obsidianweave
license=All rights reserved
java_version=25
source_url=https://github.com/itssimple/obsidianweave
issue_tracker_url=https://github.com/itssimple/.mod-issue-tracker/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22mod%3A%20Obsidian%20Weave%22
credits=
localMavenFolder=D:/git/.maven/se/itssimple/obsidian-weave/
cf.modules=forge;fabric;neoforge
cf.moduleoutput.forge=C:/CurseForge/Instances/Forge ModTest/mods/;C:/curseforge/Instances/NeoForge Test/mods/
cf.moduleoutput.fabric=C:/curseforge/Instances/Fabric Test/mods/;C:/curseforge/Instances/Quilt Test/mods/
minecraft_version=26.1
minecraft_version_range=[26.1]
common_runs_enabled=false
common_client_run_name=Common Client
common_server_run_name=Common Server
mod_name=Obsidian Weave
mod_author=NoLifeKing85
mod_id=obsidianweave
description=Shared library for all mods by NoLifeKing85
forge_version=62.0.2
forge_loader_version_range=[62,)
fabric_version=0.144.0+26.1
fabric_loader_version=0.18.4
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
mavenRepoPath=D:\Git\.maven
neoforge_version=26.1.0.1-beta
loader_version=[4,)
neo_form_version=26.1-1